server.port=8080
spring.application.name=todo-springboot-backend

logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level %logger{36} [%X{requestId:-}] - %msg%n%wEx
logging.pattern.file=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level %logger{36} [%X{requestId:-}] - %msg%n%wEx

logging.level.com.todo.backend=INFO
logging.level.com.todo.backend.service=DEBUG

